---
title: "Homework_5"
author: "Shekeira Bryan Oki"
date: "11/21/2021"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r}
library(tidyverse)
library(viridis)
library(tigris)
library(sf)
library(ggplot2)
```


##Load data
```{r}
homicide <- read.csv("homicide-data.csv")
```


##Chicago homicides
```{r}
chic_homicide <- homicide %>%
  filter(city == "Chicago")
```


##Identify longitude and latitude of Chicago homicides
```{r}
chic_homs <- st_as_sf(chic_homicide, coords = c("lon", "lat")) %>%
  st_set_crs(4269)
```


##Create map of Chicago using SF function
```{r}
chic_map <- counties(state = "IL", cb = TRUE, class = "sf")
chic_map <- chic_map %>%
  filter(COUNTYFP == "031")
```


##Create plot
```{r}
ggplot() +
  geom_sf(data = chic_map) +
  geom_sf(data = chic_homs, aes(color = disposition))
```
##Load forcats
```{r}
library(forcats)
```


#Map of 3 race groups with highest homicides
```{r}
chic_homs %>%
  mutate(victim_race = fct_lump(victim_race, n = 3)) %>%
  ggplot +
  geom_sf(data = chic_map) +
  geom_sf(aes(color = victim_race))
```

